version: '3.8'
services:
  api:
    container_name: store_api
    image: api-store
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: '${POSTGRES_DB}'
      DATABASE_HOST: '${POSTGRES_HOST}'
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - '80:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
